version: 2

general:
  branches:
    only:
      - develop

jobs:
  build:
    macos:
      xcode: "9.0"

    environment:
      PERL5LIB: "$HOME/perl5/lib/perl5"

    steps:
     - checkout
     - run: curl -L https://cpanmin.us | perl - App::cpanminus
     - run: $HOME/perl5/bin/cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
     - run: echo $PERL5LIB
     - run: $HOME/perl5/bin/cpanm -L ~/perl5 Module::Install
     - run: touch Makefile.PL
     - run: $HOME/perl5/bin/cpanm -L ~/perl5 --installdeps --verbose --notest .
     - run: $HOME/perl5/bin/cpanm -L ~/perl5 Test::Deep
     - run: $HOME/perl5/bin/cpanm -L ~/perl5 Test::More
     - run: $HOME/perl5/bin/cpanm -L ~/perl5 UNIVERSAL::require
     - run: $HOME/perl5/bin/cpanm -L ~/perl5 File::Copy::Recursive
     - run: perl Makefile.PL
     - run: make
     - run: make test
